name: pokemon-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=1.3.3
  - numpy=1.21.2
  - scikit-learn=0.24.2
  - xgboost=1.4.2
  - matplotlib=3.4.3
  - shap=0.39.0
  - pip